//! Manages the overall simulation, including the particle grid and update logic.
//!
//! The `SimulationEngine` is the main entry point for running the sand simulation.
//! It orchestrates particle interactions, physics, and state changes.
//!
//! # Example
//! ```no_run
//! use sand_simulation_engine::simulation_engine::SimulationEngine;
//! use sand_simulation_engine::material::MaterialType;
//!
//! let mut engine = SimulationEngine::new(200, 150);
//! engine.place_particle_circle(100, 50, 5, MaterialType::SAND, None);
//!
//! // In a game loop:
//! // let delta_time = ...; // Time since last frame
//! // engine.update(delta_time);
//! // Access engine.grid.cells for rendering.
//! ```

use crate::grid::Grid;
use crate::particle::Particle;
use crate::material::{MaterialType, is_liquid, is_powder, is_rigid_solid, get_material_properties, MaterialProperties};
use rand::seq::SliceRandom; // For shuffling
use rand::thread_rng; // For shuffling
use rand::Rng; // For random numbers

// --- Simulation Constants ---

/// Default ambient temperature for new particles and surroundings, in Celsius.
pub const AMBIENT_TEMP: f32 = 20.0;
/// Lifespan of a burning FUSE particle in seconds.
pub const FUSE_BURN_LIFESPAN_SEC: f32 = 4.0;
/// Target frame rate for scaling time-dependent effects (e.g., 60 FPS).
/// Used to make simulation rates consistent across different frame rates.
pub const TARGET_DT_SCALING: f32 = 60.0; 
/// Maximum temperature a particle can reach, in Celsius.
pub const MAX_TEMP: f32 = 3000.0; 
/// Rate at which particles cool down towards AMBIENT_TEMP.
pub const COOLING_RATE: f32 = 0.005;
/// Damping factor for thermal inertia for materials that resist quick temperature changes.
pub const HIGH_INERTIA_DAMPING: f32 = 0.2;

/// Heat transfer rate for FIRE when interacting with neighbors (arbitrary unit).
pub const FIRE_HEAT_TRANSFER: f32 = 60.0; 
/// Cooling effect strength when WATER interacts with FIRE (arbitrary unit).
pub const WATER_COOLING_FACTOR: f32 = 80.0;
/// Chance per second for a PLANT particle to grow if conditions are met.
pub const PLANT_GROWTH_CHANCE_PER_SEC: f32 = 0.09;
/// Y-coordinate limit above which STEAM condensation is more likely.
pub const CONDENSATION_Y_LIMIT: i32 = 5; 
/// Base chance per second for STEAM to condense anywhere if conditions are met.
pub const CONDENSATION_CHANCE_ANYWHERE_PER_SEC: f32 = 0.006;
/// Temperature buffer (in Celsius) to prevent rapid flickering between states during phase changes.
/// A particle needs to be this much above/below the threshold to change state.
pub const PHASE_CHANGE_TEMP_BUFFER: f32 = 5.0;
/// Minimum time in seconds a particle like LAVA or STEAM must remain in its state before changing due to cooling/condensation.
pub const MIN_STATE_SECONDS: f32 = 10.0; 
/// Factor by which the temperature of gas generated by ACID dissolving material is adjusted relative to the ACID's temperature.
pub const ACID_GAS_TEMP_FACTOR: f32 = 0.8;
/// Default temperature for LAVA when placed by the brush tool.
pub const LAVA_BRUSH_TEMP: f32 = 2500.0;


/// Manages the overall simulation state and logic, including the particle grid,
/// update cycles, and interactions between particles. It orchestrates the application
/// of physical rules and material behaviors to each particle in the simulation.
#[derive(Debug, Clone)]
pub struct SimulationEngine {
    /// The `Grid` struct holding all particles. Publicly accessible for rendering or direct inspection.
    pub grid: Grid,
    /// Stores a shuffled order of column indices for processing particles.
    /// This helps prevent directional bias in particle interactions. Internal state.
    pub shuffled_column_order: Vec<usize>,
}

impl SimulationEngine {
    /// Creates a new `SimulationEngine` with a grid of the specified width and height.
    ///
    /// Initializes the grid with `EMPTY` particles and shuffles the column processing order
    /// to prevent directional bias in simulations.
    ///
    /// # Arguments
    /// * `width` - The width of the simulation grid in cells.
    /// * `height` - The height of the simulation grid in cells.
    ///
    /// # Returns
    /// A new `SimulationEngine` instance.
    pub fn new(width: usize, height: usize) -> Self {
        let grid = Grid::new(width, height);
        let mut shuffled_column_order: Vec<usize> = (0..width).collect();
        shuffled_column_order.shuffle(&mut thread_rng()); 

        SimulationEngine {
            grid,
            shuffled_column_order,
        }
    }

    /// Advances the simulation by one time step.
    ///
    /// This is the main method to drive the simulation forward. It performs the following steps:
    /// 1. Resets `processed_this_step` and `moved_this_step` flags for all particles.
    /// 2. Re-shuffles the column processing order to ensure fairness and reduce bias.
    /// 3. Iterates through all particles in a specific order (bottom-up, shuffled columns)
    ///    and calls `update_particle` for each non-empty, unprocessed particle.
    ///
    /// # Arguments
    /// * `delta_time_seconds` - The time elapsed since the last update, in seconds. Used for
    ///   time-dependent calculations like lifespan and temperature changes.
    pub fn update(&mut self, delta_time_seconds: f32) {
        for y_idx in 0..self.grid.height {
            for x_idx in 0..self.grid.width {
                if let Some(particle) = self.grid.get_particle_mut(x_idx as i32, y_idx as i32) {
                    particle.processed_this_step = false; 
                    particle.moved_this_step = false;    
                }
            }
        }
        self.shuffled_column_order.shuffle(&mut thread_rng());

        for y_coord in (0..self.grid.height).rev() { 
            for &x_coord_usize in &self.shuffled_column_order {
                let x_coord = x_coord_usize as i32;
                
                let particle_exists_and_needs_processing = {
                    if let Some(p) = self.grid.get_particle(x_coord, y_coord as i32) {
                        p.material_type != MaterialType::EMPTY && !p.processed_this_step
                    } else { false }
                };

                if particle_exists_and_needs_processing {
                    self.update_particle(x_coord, y_coord as i32, delta_time_seconds);
                }
            }
        }
    }
    
    /// Internal helper to manage lifespan and burnout for a particle at (`x`, `y`).
    fn handle_lifespan_and_burnout(&mut self, x: i32, y: i32, delta_time_seconds: f32) {
        let (
            needs_update, is_fuse_to_ignite, initial_type, initial_temp, mut current_life_opt
        ) = {
            if let Some(particle) = self.grid.get_particle(x, y) {
                if particle.material_type == MaterialType::EMPTY { return; } 
                let mut needs_check_flag = false; let mut fuse_ignition_flag = false;
                if particle.material_type == MaterialType::FUSE && particle.burning {
                    needs_check_flag = true;
                    if particle.life_remaining_seconds.is_none() { fuse_ignition_flag = true; }
                } else if particle.life_remaining_seconds.is_some() { needs_check_flag = true; }
                (needs_check_flag, fuse_ignition_flag, particle.material_type, particle.temperature, particle.life_remaining_seconds)
            } else { return; }
        };

        if !needs_update { return; }
        if is_fuse_to_ignite { current_life_opt = Some(FUSE_BURN_LIFESPAN_SEC); }
        
        if let Some(mut current_life) = current_life_opt {
            current_life -= delta_time_seconds;
            if current_life <= 0.0 {
                let (base_replace_type, base_replace_temp) = match initial_type {
                    MaterialType::FIRE => (MaterialType::SMOKE, (initial_temp * 0.6).min(400.0)),
                    MaterialType::FUSE => (MaterialType::ASH, (initial_temp * 0.5).max(AMBIENT_TEMP)),
                    MaterialType::STEAM | MaterialType::SMOKE | MaterialType::TOXIC_GAS => (MaterialType::EMPTY, AMBIENT_TEMP),
                    _ => (initial_type, initial_temp), 
                };
                let final_replace_type = match initial_type {
                    MaterialType::FIRE | MaterialType::FUSE | MaterialType::STEAM | MaterialType::SMOKE | MaterialType::TOXIC_GAS => base_replace_type,
                    _ => { if get_material_properties(initial_type).lifespan_seconds.is_some() { MaterialType::EMPTY } else { initial_type } }
                };
                let final_replace_temp = if final_replace_type == MaterialType::EMPTY { AMBIENT_TEMP } else { base_replace_temp };
                self.grid.set_particle(x, y, Particle::new(x, y, final_replace_type, final_replace_temp));
            } else {
                if let Some(particle_mut) = self.grid.get_particle_mut(x, y) {
                    particle_mut.life_remaining_seconds = Some(current_life);
                    if particle_mut.material_type == MaterialType::FUSE && particle_mut.burning {
                        let fuse_melt_temp = get_material_properties(MaterialType::FUSE).melt_temperature.unwrap_or(MAX_TEMP);
                        particle_mut.temperature = (particle_mut.temperature + 5.0 * delta_time_seconds * TARGET_DT_SCALING).min(fuse_melt_temp); 
                        particle_mut.invalidate_color_cache();
                    } else if get_material_properties(particle_mut.material_type).lifespan_seconds.is_some() {
                        particle_mut.invalidate_color_cache();
                    }
                }
            }
        }
    }

    /// Internal helper to update the temperature of a particle at (`x`, `y`).
    fn update_temperature(&mut self, x: i32, y: i32, delta_time_seconds: f32) {
        let (current_temp_val, mut base_conductivity, heat_generation, particle_type) = {
            if let Some(particle) = self.grid.get_particle(x, y) {
                if particle.material_type == MaterialType::EMPTY { return; }
                let props = particle.get_material_properties();
                (particle.temperature, props.thermal_conductivity, props.heat_generation, particle.material_type)
            } else { return; }
        };

        match particle_type {
            MaterialType::GENERATOR => base_conductivity *= 0.1,
            MaterialType::STONE | MaterialType::GLASS => base_conductivity *= 0.3,
            _ => {}
        }

        let mut neighbor_temp_sum = 0.0; let mut neighbor_conductivity_sum = 0.0; let mut neighbor_count = 0; 
        let empty_props = get_material_properties(MaterialType::EMPTY);
        let empty_conductivity = empty_props.thermal_conductivity;

        for dy_offset in -1..=1 { for dx_offset in -1..=1 { 
            if dx_offset == 0 && dy_offset == 0 { continue; }
            let nx = x + dx_offset; let ny = y + dy_offset;
            let (n_temp, n_cond) = if let Some(neighbor) = self.grid.get_particle(nx, ny) {
                if neighbor.material_type != MaterialType::EMPTY { 
                    (neighbor.temperature, neighbor.get_material_properties().thermal_conductivity) 
                } else { (AMBIENT_TEMP, empty_conductivity) }
            } else { (AMBIENT_TEMP, empty_conductivity) };
            let dist_factor = if dx_offset == 0 || dy_offset == 0 { 1.0 } else { 0.707 };
            neighbor_temp_sum += n_temp * n_cond * dist_factor;
            neighbor_conductivity_sum += n_cond * dist_factor;
            neighbor_count +=1;
        }}

        let mut new_temp = current_temp_val;
        let scaled_dt = delta_time_seconds * TARGET_DT_SCALING;

        if neighbor_count > 0 && (base_conductivity > 0.001 || neighbor_conductivity_sum > 0.001) { 
            let total_conductivity = base_conductivity + neighbor_conductivity_sum;
            if total_conductivity > 0.001 { 
                let weighted_avg_temp = (current_temp_val * base_conductivity + neighbor_temp_sum) / total_conductivity;
                let mut delta_temp_val = (weighted_avg_temp - current_temp_val) * (base_conductivity * 0.8).min(0.5); 
                match particle_type {
                    MaterialType::LAVA | MaterialType::STONE | MaterialType::GLASS | MaterialType::ICE => { delta_temp_val *= HIGH_INERTIA_DAMPING; }
                    _ => {}
                }
                delta_temp_val = delta_temp_val.max(-50.0).min(50.0) * scaled_dt; 
                new_temp += delta_temp_val;
            }
        }
        new_temp += (AMBIENT_TEMP - new_temp) * COOLING_RATE * base_conductivity * scaled_dt;
        if heat_generation > 0.0 { new_temp += heat_generation * scaled_dt; }
        new_temp = new_temp.clamp(-273.15, MAX_TEMP);

        if (new_temp - current_temp_val).abs() > 0.01 { 
            if let Some(particle_mut) = self.grid.get_particle_mut(x, y) {
                particle_mut.temperature = new_temp;
                particle_mut.invalidate_color_cache(); 
            }
        }
    }
    
    /// Simulates an explosion centered at (`cx`, `cy`) with a given `radius`.
    ///
    /// The particle at the center is replaced with `EMPTY`. Particles within the `radius`
    /// are heated significantly, and may change type to `FIRE` or `SMOKE`, or other
    /// transformations like `STONE` to `SAND`. The effect strength diminishes with distance
    /// from the center. Affected particles are marked as processed for the current step.
    ///
    /// # Arguments
    /// * `cx` - The x-coordinate of the explosion's center.
    /// * `cy` - The y-coordinate of the explosion's center.
    /// * `radius` - The radius of the explosion's effect.
    pub fn explode(&mut self, cx: i32, cy: i32, radius: f32) {
        self.grid.set_particle(cx, cy, Particle::new(cx, cy, MaterialType::EMPTY, AMBIENT_TEMP));
        let mut affected_particles_coords: Vec<(i32, i32, f32)> = Vec::new();
        let radius_sq = radius * radius;
        let r_bound = radius.ceil() as i32;

        for dy_offset in -r_bound..=r_bound {
            for dx_offset in -r_bound..=r_bound {
                if dx_offset == 0 && dy_offset == 0 { continue; } 
                let dist_sq = (dx_offset as f32 * dx_offset as f32) + (dy_offset as f32 * dy_offset as f32);
                if dist_sq <= radius_sq {
                    let px = cx + dx_offset; let py = cy + dy_offset;
                    if self.grid.is_valid(px, py) {
                        if let Some(p) = self.grid.get_particle(px, py) {
                            if p.material_type != MaterialType::EMPTY {
                                affected_particles_coords.push((px, py, dist_sq));
                            }
                        }
                    }
                }
            }
        }
        
        let fire_props = get_material_properties(MaterialType::FIRE);
        let default_fire_lifespan = fire_props.lifespan_seconds.unwrap_or(1.0);
        let smoke_props = get_material_properties(MaterialType::SMOKE);
        let default_smoke_lifespan = smoke_props.lifespan_seconds.unwrap_or(3.0);

        for (px, py, dist_sq) in affected_particles_coords {
            if let Some(particle) = self.grid.get_particle_mut(px, py) {
                if particle.material_type == MaterialType::EMPTY { continue; }
                let dist = dist_sq.sqrt();
                let effect_strength = (1.0 - (dist / radius)).max(0.0);
                particle.temperature = (particle.temperature + 1500.0 * effect_strength).min(MAX_TEMP);
                let original_type = particle.material_type; 
                if rand::random::<f32>() < effect_strength * 0.95 && original_type != MaterialType::GENERATOR {
                    let new_type; let new_lifespan;
                    if rand::random::<f32>() < 0.6 * effect_strength && original_type != MaterialType::WATER && original_type != MaterialType::ICE {
                        new_type = MaterialType::FIRE;
                        new_lifespan = Some(default_fire_lifespan * effect_strength * 0.5);
                    } else {
                        new_type = MaterialType::SMOKE;
                        new_lifespan = Some(default_smoke_lifespan * effect_strength);
                    }
                    particle.material_type = new_type;
                    particle.life_remaining_seconds = new_lifespan;
                    particle.time_in_state_seconds = 0.0;
                    particle.burning = false; 
                } else {
                    if (original_type == MaterialType::STONE || original_type == MaterialType::GLASS) && rand::random::<f32>() < effect_strength * 0.3 {
                        particle.material_type = MaterialType::SAND;
                        particle.time_in_state_seconds = 0.0; 
                    } else if original_type == MaterialType::WOOD && rand::random::<f32>() < effect_strength * 0.5 {
                        particle.material_type = MaterialType::ASH;
                        particle.time_in_state_seconds = 0.0;
                    }
                }
                particle.invalidate_color_cache();
                particle.processed_this_step = true;
            }
        }
    }
    
    /// Internal helper to handle state changes and special material effects for a particle at (`x`, `y`).
    fn handle_state_changes_and_effects(&mut self, x: i32, y: i32, delta_time_seconds: f32) {
        let (initial_particle_type, initial_temp, initial_time_in_state, initial_burning_state) = {
            if let Some(p) = self.grid.get_particle(x, y) {
                if p.material_type == MaterialType::EMPTY { return; }
                (p.material_type, p.temperature, p.time_in_state_seconds, p.burning)
            } else { return; }
        };
        let initial_props = get_material_properties(initial_particle_type);
        let dt_scale_update = delta_time_seconds * TARGET_DT_SCALING; 
        let default_fire_lifespan_val = get_material_properties(MaterialType::FIRE).lifespan_seconds.unwrap_or(1.0);

        if let Some(ignition_temp_threshold) = initial_props.ignition_temperature {
            if initial_temp >= ignition_temp_threshold && initial_props.flammability > 0.0 && !initial_burning_state {
                let mut external_ignition_source = false;
                let mut highest_neighbor_temp_for_ignition = initial_temp;
                for dy_offset in -1..=1 { for dx_offset in -1..=1 { 
                    if dx_offset == 0 && dy_offset == 0 { continue; }
                    if let Some(n) = self.grid.get_particle(x + dx_offset, y + dy_offset) {
                        if n.material_type == MaterialType::FIRE || n.material_type == MaterialType::LAVA || (n.material_type == MaterialType::FUSE && n.burning) {
                            external_ignition_source = true;
                            highest_neighbor_temp_for_ignition = highest_neighbor_temp_for_ignition.max(n.temperature);
                            break; 
                        }
                    }
                } if external_ignition_source { break; }}

                let mut new_type_after_ignition = None; 
                match initial_particle_type {
                    MaterialType::PLANT | MaterialType::WOOD | MaterialType::COAL | MaterialType::OIL | MaterialType::GASOLINE => {
                        if external_ignition_source || initial_temp > ignition_temp_threshold + 100.0 { 
                            new_type_after_ignition = Some(MaterialType::FIRE);
                        }
                    }
                    MaterialType::GUNPOWDER => { 
                        self.explode(x, y, initial_props.explosive_yield.unwrap_or(4.0));
                        return; 
                    }
                    MaterialType::FUSE => { 
                        if external_ignition_source {
                            if let Some(p_mut) = self.grid.get_particle_mut(x,y) {
                                p_mut.burning = true; 
                                p_mut.temperature = p_mut.temperature.max(ignition_temp_threshold + 50.0); 
                                p_mut.invalidate_color_cache();
                            }
                        }
                    }
                    _ => {} 
                }
                if let Some(ignited_type) = new_type_after_ignition {
                    if ignited_type == MaterialType::FIRE {
                        let mut fire_temp = highest_neighbor_temp_for_ignition.max(800.0); 
                        let mut fire_life = default_fire_lifespan_val;
                        if initial_particle_type == MaterialType::WOOD { fire_life = 3.0; fire_temp = fire_temp.max(800.0); }
                        if initial_particle_type == MaterialType::COAL { fire_life = 4.0; fire_temp = fire_temp.max(900.0); }
                        
                        if let Some(p_mut) = self.grid.get_particle_mut(x, y) {
                            p_mut.material_type = MaterialType::FIRE;
                            p_mut.temperature = fire_temp;
                            p_mut.life_remaining_seconds = Some(fire_life);
                            p_mut.time_in_state_seconds = 0.0; 
                            p_mut.burning = false; 
                            p_mut.invalidate_color_cache();
                        }
                        return; 
                    }
                }
            }
        }
        if let Some(melt_temp) = initial_props.melt_temperature {
            if initial_temp >= melt_temp + PHASE_CHANGE_TEMP_BUFFER {
                let new_type = match initial_particle_type {
                    MaterialType::SAND => Some(MaterialType::GLASS), MaterialType::GLASS => Some(MaterialType::LAVA),
                    MaterialType::ICE => Some(MaterialType::WATER), _ => None,
                };
                if let Some(nt) = new_type { if let Some(p_mut) = self.grid.get_particle_mut(x,y) { p_mut.change_type(nt, None); } return; }
            }
        }
        if let Some(boil_temp) = initial_props.boil_temperature {
            if initial_temp >= boil_temp + PHASE_CHANGE_TEMP_BUFFER {
                let new_type = match initial_particle_type {
                    MaterialType::WATER => Some(MaterialType::STEAM), MaterialType::ACID => Some(MaterialType::TOXIC_GAS),
                    MaterialType::SLIME => Some(MaterialType::TOXIC_GAS), _ => None,
                };
                if let Some(nt) = new_type { if let Some(p_mut) = self.grid.get_particle_mut(x,y) { p_mut.change_type(nt, None); } return; }
            }
        }
        if let Some(freeze_temp) = initial_props.freeze_temperature {
            if initial_temp <= freeze_temp - PHASE_CHANGE_TEMP_BUFFER {
                let mut new_type = None;
                match initial_particle_type {
                    MaterialType::LAVA => new_type = Some(MaterialType::STONE), 
                    MaterialType::WATER => new_type = Some(MaterialType::ICE),   
                    MaterialType::STEAM => { 
                        if initial_time_in_state >= MIN_STATE_SECONDS {
                             let condensation_chance = if y < CONDENSATION_Y_LIMIT { 1.0 } else { CONDENSATION_CHANCE_ANYWHERE_PER_SEC * delta_time_seconds };
                             if rand::random::<f32>() < condensation_chance { new_type = Some(MaterialType::WATER); }
                        }
                    } _ => {}
                }
                if let Some(nt) = new_type { if let Some(p_mut) = self.grid.get_particle_mut(x,y) { p_mut.change_type(nt, None); } return; }
            }
        }
        let current_particle_type = self.grid.get_particle(x,y).map_or(initial_particle_type, |p| p.material_type);
        match current_particle_type {
            MaterialType::FIRE => {
                let mut fuel_found = false; let mut extinguish_fire = false;
                let fire_temp = self.grid.get_particle(x,y).unwrap().temperature; 
                
                for dy_offset in -1..=1 { for dx_offset in -1..=1 { 
                    if dx_offset == 0 && dy_offset == 0 { continue; }
                    let nx = x + dx_offset; let ny = y + dy_offset; if !self.grid.is_valid(nx,ny) { continue; }
                    let (n_type, n_temp, n_is_burning_fuse, n_flammability, n_ign_temp, n_explosive_yield) = {
                        if let Some(n_particle) = self.grid.get_particle(nx,ny) {
                            let n_props = n_particle.get_material_properties();
                            (n_particle.material_type, n_particle.temperature, (n_particle.material_type == MaterialType::FUSE && n_particle.burning), n_props.flammability, n_props.ignition_temperature, n_props.explosive_yield)
                        } else { continue; } 
                    };
                    if n_type == MaterialType::WATER || n_type == MaterialType::ICE {
                        if let Some(fire_p_mut) = self.grid.get_particle_mut(x,y) {
                            fire_p_mut.temperature -= WATER_COOLING_FACTOR * dt_scale_update; 
                            fire_p_mut.life_remaining_seconds = Some(fire_p_mut.life_remaining_seconds.unwrap_or(default_fire_lifespan_val) - 10.0 * delta_time_seconds);
                            fire_p_mut.invalidate_color_cache();
                        }
                        if rand::random::<f32>() < 0.5 * dt_scale_update { 
                            if let Some(n_p_mut) = self.grid.get_particle_mut(nx,ny) {
                                if n_type == MaterialType::WATER { n_p_mut.change_type(MaterialType::STEAM, None); }
                                else if n_type == MaterialType::ICE { n_p_mut.change_type(MaterialType::WATER, None); }
                            }
                        }
                        if self.grid.get_particle(x,y).unwrap().temperature < 300.0 { extinguish_fire = true; }
                    } else if n_flammability > 0.0 && n_type != MaterialType::FIRE { 
                        fuel_found = true;
                        if let Some(n_ign_t) = n_ign_temp { if n_temp >= n_ign_t {
                            if n_type == MaterialType::GUNPOWDER { self.explode(nx, ny, n_explosive_yield.unwrap_or(4.0)); }
                            else if n_type == MaterialType::FUSE && !n_is_burning_fuse { 
                                if let Some(n_p_mut) = self.grid.get_particle_mut(nx,ny) {
                                    n_p_mut.burning = true; n_p_mut.life_remaining_seconds = Some(FUSE_BURN_LIFESPAN_SEC);
                                    n_p_mut.temperature = n_temp.max(n_ign_t + 50.0); n_p_mut.invalidate_color_cache();
                                }
                            } else { 
                                let mut new_fire_temp = n_temp.max(800.0); let mut new_fire_life = default_fire_lifespan_val;
                                if n_type == MaterialType::WOOD { new_fire_life = 3.0; new_fire_temp = new_fire_temp.max(800.0); }
                                if n_type == MaterialType::COAL { new_fire_life = 4.0; new_fire_temp = new_fire_temp.max(900.0); }
                                if let Some(n_p_mut) = self.grid.get_particle_mut(nx,ny) {
                                    n_p_mut.material_type = MaterialType::FIRE; n_p_mut.temperature = new_fire_temp;
                                    n_p_mut.life_remaining_seconds = Some(new_fire_life); n_p_mut.time_in_state_seconds = 0.0;
                                    n_p_mut.burning = false; n_p_mut.invalidate_color_cache();
                                }
                            }
                        }}
                    }
                }} 
                if let Some(fire_p_mut) = self.grid.get_particle_mut(x,y) {
                    if fuel_found && fire_p_mut.life_remaining_seconds.is_some() {
                        fire_p_mut.life_remaining_seconds = Some(fire_p_mut.life_remaining_seconds.unwrap().max(default_fire_lifespan_val));
                    }
                }
                if !extinguish_fire && rand::random::<f32>() < 0.1 * dt_scale_update { 
                    let smoke_x = x + if rand::random::<f32>() < 0.5 { -1 } else { 1 }; let smoke_y = y - 1;
                    if self.grid.is_valid(smoke_x, smoke_y) && self.grid.get_particle(smoke_x, smoke_y).map_or(false, |p| p.material_type == MaterialType::EMPTY) {
                        self.grid.set_particle(smoke_x, smoke_y, Particle::new(smoke_x, smoke_y, MaterialType::SMOKE, fire_temp * 0.5));
                    }
                }
                if extinguish_fire {
                    let final_fire_temp = self.grid.get_particle(x,y).map_or(AMBIENT_TEMP, |p|p.temperature);
                    self.grid.set_particle(x,y, Particle::new(x,y,MaterialType::SMOKE, final_fire_temp)); return;
                }
            }
            MaterialType::FUSE if initial_burning_state => { 
                for dy_offset in -1..=1 { for dx_offset in -1..=1 { 
                    if dx_offset == 0 && dy_offset == 0 { continue; }
                    let nx = x + dx_offset; let ny = y + dy_offset; if !self.grid.is_valid(nx,ny) { continue; }
                    let (n_type, n_temp, n_is_burning_fuse, n_flammability, n_ign_temp, n_explosive_yield) = {
                         if let Some(n_particle) = self.grid.get_particle(nx,ny) {
                            let n_props = n_particle.get_material_properties();
                            (n_particle.material_type, n_particle.temperature, (n_particle.material_type == MaterialType::FUSE && n_particle.burning), n_props.flammability, n_props.ignition_temperature, n_props.explosive_yield)
                        } else { continue; }
                    };
                    if let Some(n_p_mut) = self.grid.get_particle_mut(nx,ny) {
                        n_p_mut.temperature = (n_p_mut.temperature + 20.0 * dt_scale_update).min(MAX_TEMP); 
                        n_p_mut.invalidate_color_cache();
                    }
                    if let Some(n_ign_t) = n_ign_temp { if n_temp >= n_ign_t {
                        if n_type == MaterialType::FUSE && !n_is_burning_fuse { 
                            if let Some(n_p_mut) = self.grid.get_particle_mut(nx,ny) {
                                n_p_mut.burning = true; n_p_mut.life_remaining_seconds = Some(FUSE_BURN_LIFESPAN_SEC);
                                n_p_mut.temperature = n_temp.max(n_ign_t + 50.0); n_p_mut.invalidate_color_cache();
                            }
                        } else if n_type == MaterialType::GUNPOWDER { self.explode(nx, ny, n_explosive_yield.unwrap_or(4.0)); }
                        else if n_flammability > 0.0 && n_type != MaterialType::FIRE { 
                            let mut new_fire_temp = n_temp.max(800.0); let mut new_fire_life = default_fire_lifespan_val;
                            if n_type == MaterialType::WOOD { new_fire_life = 3.0; new_fire_temp = new_fire_temp.max(800.0); }
                            if n_type == MaterialType::COAL { new_fire_life = 4.0; new_fire_temp = new_fire_temp.max(900.0); }
                            if let Some(n_p_mut) = self.grid.get_particle_mut(nx,ny) {
                                n_p_mut.material_type = MaterialType::FIRE; n_p_mut.temperature = new_fire_temp;
                                n_p_mut.life_remaining_seconds = Some(new_fire_life); n_p_mut.time_in_state_seconds = 0.0;
                                n_p_mut.burning = false; n_p_mut.invalidate_color_cache();
                            }
                        }
                    }}
                }}
            }
            MaterialType::LAVA => { 
                 for dy_offset in -1..=1 { for dx_offset in -1..=1 { 
                    if dx_offset == 0 && dy_offset == 0 { continue; }
                    let nx = x + dx_offset; let ny = y + dy_offset; if !self.grid.is_valid(nx,ny) { continue; }
                    let (n_type, n_temp, n_is_burning_fuse, n_flammability, n_ign_temp, n_explosive_yield) = {
                        if let Some(n_particle) = self.grid.get_particle(nx,ny) {
                            let n_props = n_particle.get_material_properties();
                            (n_particle.material_type, n_particle.temperature, (n_particle.material_type == MaterialType::FUSE && n_particle.burning), n_props.flammability, n_props.ignition_temperature, n_props.explosive_yield)
                        } else { continue; }
                    };
                    if let Some(n_ign_t) = n_ign_temp { if n_flammability > 0.0 && n_type != MaterialType::FIRE { 
                        if n_temp >= n_ign_t { 
                            if n_type == MaterialType::GUNPOWDER { self.explode(nx, ny, n_explosive_yield.unwrap_or(4.0)); }
                            else if n_type == MaterialType::FUSE && !n_is_burning_fuse {
                                 if let Some(n_p_mut) = self.grid.get_particle_mut(nx,ny) {
                                    n_p_mut.burning = true; n_p_mut.life_remaining_seconds = Some(FUSE_BURN_LIFESPAN_SEC);
                                    n_p_mut.temperature = n_temp.max(n_ign_t + 50.0); n_p_mut.invalidate_color_cache();
                                }
                            } else { 
                                let mut new_fire_temp = n_temp.max(1000.0); 
                                let mut new_fire_life = default_fire_lifespan_val;
                                if n_type == MaterialType::WOOD { new_fire_life = 3.0; } if n_type == MaterialType::COAL { new_fire_life = 4.0; }
                                if let Some(n_p_mut) = self.grid.get_particle_mut(nx,ny) {
                                    n_p_mut.material_type = MaterialType::FIRE; n_p_mut.temperature = new_fire_temp;
                                    n_p_mut.life_remaining_seconds = Some(new_fire_life); n_p_mut.time_in_state_seconds = 0.0;
                                    n_p_mut.burning = false; n_p_mut.invalidate_color_cache();
                                }
                            }
                        }
                    }}
                 }}
            }
            MaterialType::ACID => { 
                let corrosive_power = initial_props.corrosive_power;
                if corrosive_power > 0.0 {
                    let mut consumed_acid_this_step = false;
                    for dy_offset in -1..=1 { for dx_offset in -1..=1 {
                        if (dx_offset == 0 && dy_offset == 0) || (dx_offset != 0 && dy_offset != 0) { continue; } 
                        let nx = x + dx_offset; let ny = y + dy_offset; if !self.grid.is_valid(nx,ny) { continue; }
                        
                        let n_type_opt = self.grid.get_particle(nx,ny).map(|p|p.material_type);
                        if let Some(neighbor_material_type) = n_type_opt {
                            let immune_to_acid = [MaterialType::EMPTY, MaterialType::ACID, MaterialType::GLASS, MaterialType::GENERATOR];
                            if !immune_to_acid.contains(&neighbor_material_type) { 
                                if rand::random::<f32>() < corrosive_power * dt_scale_update { 
                                    let mut dissolve_neighbor = true;
                                    if neighbor_material_type == MaterialType::STONE && rand::random::<f32>() < 0.3 { 
                                        if let Some(n_p_mut) = self.grid.get_particle_mut(nx,ny) { n_p_mut.change_type(MaterialType::SAND, None); }
                                        dissolve_neighbor = false;
                                    }
                                    if dissolve_neighbor { 
                                        let acid_temp = self.grid.get_particle(x,y).map_or(AMBIENT_TEMP, |p| p.temperature);
                                        let gas_spawn_temp = acid_temp * ACID_GAS_TEMP_FACTOR;
                                        self.grid.set_particle(nx,ny, Particle::new(nx,ny,MaterialType::EMPTY, AMBIENT_TEMP)); 
                                        
                                        let gx1 = nx; let gy1 = ny -1; 
                                        if self.grid.is_valid(gx1, gy1) && self.grid.get_particle(gx1,gy1).map_or(false, |p|p.material_type == MaterialType::EMPTY) {
                                            self.grid.set_particle(gx1,gy1, Particle::new(gx1,gy1,MaterialType::TOXIC_GAS, gas_spawn_temp));
                                        } else { 
                                            let gx2 = x; let gy2 = y -1;
                                            if self.grid.is_valid(gx2, gy2) && self.grid.get_particle(gx2,gy2).map_or(false, |p|p.material_type == MaterialType::EMPTY) {
                                                self.grid.set_particle(gx2,gy2, Particle::new(gx2,gy2,MaterialType::TOXIC_GAS, gas_spawn_temp));
                                            }
                                        }
                                    }
                                    if rand::random::<f32>() < 0.05 * dt_scale_update { 
                                        self.grid.set_particle(x,y, Particle::new(x,y,MaterialType::EMPTY, AMBIENT_TEMP));
                                        consumed_acid_this_step = true; break; 
                                    }
                                }
                            }
                        }
                    } if consumed_acid_this_step { return; }}
                }
            }
            MaterialType::PLANT => { 
                let mut has_adjacent_water = false;
                let mut empty_neighbors_coords: Vec<(i32,i32)> = Vec::new(); 
                let plant_temp = initial_temp; 

                for dy_offset in -1..=1 { for dx_offset in -1..=1 {
                    if (dx_offset == 0 && dy_offset == 0) || (dx_offset != 0 && dy_offset != 0) { continue; } 
                    let nx = x + dx_offset; let ny = y + dy_offset; if !self.grid.is_valid(nx,ny) { continue; }
                    if let Some(n) = self.grid.get_particle(nx,ny) {
                        if n.material_type == MaterialType::WATER { has_adjacent_water = true; }
                        else if n.material_type == MaterialType::EMPTY { empty_neighbors_coords.push((nx,ny));}
                    }
                }}
                if has_adjacent_water && !empty_neighbors_coords.is_empty() && plant_temp > AMBIENT_TEMP && plant_temp < 50.0 {
                    if rand::random::<f32>() < PLANT_GROWTH_CHANCE_PER_SEC * delta_time_seconds { 
                        if let Some(&target_coord) = empty_neighbors_coords.choose(&mut rand::thread_rng()) { 
                            self.grid.set_particle(target_coord.0, target_coord.1, Particle::new(target_coord.0, target_coord.1, MaterialType::PLANT, plant_temp));
                        }
                    }
                }
                if has_adjacent_water && plant_temp > AMBIENT_TEMP && plant_temp < 50.0 {
                    if rand::random::<f32>() < PLANT_GROWTH_CHANCE_PER_SEC * delta_time_seconds * 0.5 { 
                        let mut converted_water_this_step = false;
                        for dy_offset in -1..=1 { for dx_offset in -1..=1 { 
                             if (dx_offset == 0 && dy_offset == 0) || (dx_offset != 0 && dy_offset != 0) { continue; }
                             let nx = x + dx_offset; let ny = y + dy_offset; if self.grid.is_valid(nx,ny) {
                                 if let Some(n_mut) = self.grid.get_particle_mut(nx,ny) {
                                     if n_mut.material_type == MaterialType::WATER {
                                         n_mut.change_type(MaterialType::PLANT, Some(plant_temp));
                                         converted_water_this_step = true; break; 
                                     }
                                 }
                             }
                        } if converted_water_this_step {}}
                    }
                }
                for dy_offset in -1..=1 { for dx_offset in -1..=1 { 
                    if dx_offset == 0 && dy_offset == 0 { continue; }
                    let nx = x + dx_offset; let ny = y + dy_offset; if self.grid.is_valid(nx,ny) {
                        if let Some(n) = self.grid.get_particle(nx,ny) {
                            if n.material_type == MaterialType::TOXIC_GAS {
                                let toxic_gas_props = n.get_material_properties();
                                if rand::random::<f32>() < toxic_gas_props.corrosive_power * 5.0 * dt_scale_update { 
                                    self.grid.set_particle(x,y, Particle::new(x,y,MaterialType::EMPTY, AMBIENT_TEMP)); return; 
                                }
                            }
                        }
                    }
                }}
            }
            _ => {} 
        }
    }

    /// Orchestrates all updates for a single particle at (`x`, `y`) for the current time step (`delta_time_seconds`).
    /// This is the core of the simulation logic for an individual particle.
    /// The order of operations is crucial:
    /// 1. Mark as processed to prevent multiple updates in one simulation step.
    /// 2. Handle lifespan and burnout (particle might turn to EMPTY).
    /// 3. Update temperature based on neighbors and material properties.
    /// 4. Handle state changes and special effects (e.g., melting, burning, growing; particle might turn to EMPTY).
    /// 5. Increment time in the current state (for state-duration specific logic).
    /// 6. Handle physical movement.
    /// After steps 2, 3, and 4, it re-checks if the particle still exists and is not EMPTY before proceeding.
    fn update_particle(&mut self, x: i32, y: i32, delta_time_seconds: f32) {
        if let Some(p) = self.grid.get_particle_mut(x, y) {
            if p.processed_this_step { return; } 
            p.processed_this_step = true;
        } else { return; }

        self.handle_lifespan_and_burnout(x, y, delta_time_seconds);
        if self.grid.get_particle(x,y).map_or(true, |p| p.material_type == MaterialType::EMPTY) { return; }

        self.update_temperature(x, y, delta_time_seconds);
        if self.grid.get_particle(x,y).map_or(true, |p| p.material_type == MaterialType::EMPTY) { return; }
        
        self.handle_state_changes_and_effects(x, y, delta_time_seconds);
        if self.grid.get_particle(x,y).map_or(true, |p| p.material_type == MaterialType::EMPTY) { return; }

        if let Some(p) = self.grid.get_particle_mut(x, y) {
           if p.material_type != MaterialType::EMPTY { p.time_in_state_seconds += delta_time_seconds; } 
           else { return; }
        } else { return; }

        if self.grid.get_particle(x,y).map_or(true, |p| p.material_type == MaterialType::EMPTY) { return; }
        self.handle_movement(x, y);
    }

    /// Simulates the physical movement of the particle at (`x`, `y`) based on its properties
    /// (density, phase) and interactions with neighboring particles.
    /// This includes gravity, buoyancy, falling into empty spaces, displacing lighter particles,
    /// splashing into liquids, diagonal movement, and horizontal spreading/piling for liquids/powders.
    /// The `moved_this_step` flag on particles is used and updated here to enable certain behaviors like liquid momentum.
    pub fn handle_movement(&mut self, x: i32, y: i32) {
        let initial_particle_type;
        let initial_density;
        let initial_props_is_gas;
        let initial_props_is_liquid;
        let initial_props_is_solid;
        let initial_particle_moved_this_step; 

        { 
            let p_check_opt = self.grid.get_particle(x, y);
            if p_check_opt.is_none() { return; } 
            let p_check = p_check_opt.unwrap();
            if p_check.material_type == MaterialType::EMPTY { return; } 
            if p_check.material_type == MaterialType::GENERATOR { return; }
            
            let props = p_check.get_material_properties();
            initial_particle_type = p_check.material_type;
            initial_density = props.density;
            initial_props_is_gas = initial_density < 0.0; 
            initial_props_is_liquid = is_liquid(initial_particle_type);
            initial_props_is_solid = !initial_props_is_gas && !initial_props_is_liquid;
            initial_particle_moved_this_step = p_check.moved_this_step; 
        }

        let vert_dir: i32 = if initial_props_is_gas { -1 } else { 1 };
        let ny = y + vert_dir; 

        if initial_props_is_solid && vert_dir == 1 { 
            let mut splashed = false;
            if self.grid.is_valid(x, ny) { 
                if let Some(target_below_type) = self.grid.get_particle(x, ny).map(|p| p.material_type) {
                    if is_liquid(target_below_type) { 
                        let initial_splash_dx = if rand::random::<f32>() < 0.5 { -1 } else { 1 }; 
                        for i in 0..2 { 
                            let current_splash_dx = if i == 0 { initial_splash_dx } else { -initial_splash_dx };
                            let splash_x = x + current_splash_dx; let splash_y = y; 
                            if self.grid.is_valid(splash_x, splash_y) && self.grid.get_particle(splash_x, splash_y).map_or(false, |p| p.material_type == MaterialType::EMPTY) {
                                let falling_solid_clone = self.grid.get_particle(x, y).unwrap().clone();
                                let liquid_to_splash_clone = self.grid.get_particle(x, ny).unwrap().clone();
                                self.grid.set_particle(splash_x, splash_y, liquid_to_splash_clone);
                                if let Some(p) = self.grid.get_particle_mut(splash_x, splash_y) { p.moved_this_step = true; }
                                self.grid.set_particle(x, ny, falling_solid_clone);
                                if let Some(p) = self.grid.get_particle_mut(x, ny) { p.moved_this_step = true; }
                                self.grid.set_particle(x, y, Particle::new(x, y, MaterialType::EMPTY, AMBIENT_TEMP));
                                splashed = true; break; 
                            }
                        }
                    }
                }
            }
            if splashed { return; } 
        }

        if !self.grid.is_valid(x, ny) { return; } 
        
        if let Some(target_type_at_ny) = self.grid.get_particle(x, ny).map(|p| p.material_type) {
            if target_type_at_ny == MaterialType::GENERATOR {  }
            else if target_type_at_ny == MaterialType::EMPTY { 
                self.grid.swap_particles(x, y, x, ny);
                if let Some(p_now_at_ny) = self.grid.get_particle_mut(x, ny) { p_now_at_ny.moved_this_step = true; }
                return;
            } else { 
                let target_density_at_ny = self.grid.get_particle(x, ny).unwrap().get_material_properties().density;
                let should_push = if initial_props_is_gas { target_density_at_ny > initial_density } else { initial_density > target_density_at_ny };
                
                if should_push { 
                    let initial_push_dx = if rand::random::<f32>() < 0.5 { -1 } else { 1 }; 
                    let mut pushed = false;
                    for i in 0..2 { 
                        let current_push_dx = if i == 0 { initial_push_dx } else { -initial_push_dx };
                        let push_target_x = x + current_push_dx; let push_target_y = ny;
                        if self.grid.is_valid(push_target_x, push_target_y) && self.grid.get_particle(push_target_x, push_target_y).map_or(false, |p| p.material_type == MaterialType::EMPTY) {
                            let particle_to_push_clone = self.grid.get_particle(x, ny).unwrap().clone();
                            let current_particle_clone = self.grid.get_particle(x, y).unwrap().clone();
                            self.grid.set_particle(push_target_x, push_target_y, particle_to_push_clone);
                            if let Some(p) = self.grid.get_particle_mut(push_target_x, push_target_y) { p.moved_this_step = true; }
                            self.grid.set_particle(x, ny, current_particle_clone);
                            if let Some(p) = self.grid.get_particle_mut(x, ny) { p.moved_this_step = true; }
                            self.grid.set_particle(x, y, Particle::new(x, y, MaterialType::EMPTY, AMBIENT_TEMP));
                            pushed = true; break; 
                        }
                    }
                    if pushed { return; } 
                }

                let density_allows_swap = if initial_props_is_gas { target_density_at_ny > initial_density } else { initial_density > target_density_at_ny };
                if density_allows_swap { 
                    self.grid.swap_particles(x, y, x, ny);
                    if let Some(p_now_at_ny) = self.grid.get_particle_mut(x, ny) { p_now_at_ny.moved_this_step = true; }
                    if let Some(p_now_at_xy) = self.grid.get_particle_mut(x, y) { if p_now_at_xy.material_type != MaterialType::EMPTY { p_now_at_xy.moved_this_step = true; }}
                    return; 
                }
            }
        } 

        if vert_dir == 1 && is_powder(initial_particle_type) { 
            if let Some(p_below) = self.grid.get_particle(x, y + 1) { if is_rigid_solid(p_below.material_type) { return; } }
        }

        if !is_rigid_solid(initial_particle_type) { 
            let dx1 = if rand::random::<f32>() < 0.5 { -1 } else { 1 }; 
            for &check_dx in &[dx1, -dx1] { 
                let diag_x = x + check_dx; let diag_y = y + vert_dir;
                if self.grid.is_valid(diag_x, diag_y) && self.grid.get_particle(diag_x, diag_y).map_or(false, |p| p.material_type == MaterialType::EMPTY) {
                    let mut vertical_blocked = false;
                    if let Some(vn) = self.grid.get_particle(x, ny) { 
                        if vn.material_type != MaterialType::EMPTY {
                            if vn.material_type == MaterialType::GENERATOR { vertical_blocked = true; }
                            else { let vn_density = vn.get_material_properties().density;
                                   if initial_props_is_gas { if vn_density <= initial_density { vertical_blocked = true; }} 
                                   else { if vn_density >= initial_density { vertical_blocked = true; }}}
                        }
                    } else { vertical_blocked = true; } 
                    
                    if vertical_blocked { 
                        self.grid.swap_particles(x, y, diag_x, diag_y);
                        if let Some(p_now_at_diag) = self.grid.get_particle_mut(diag_x, diag_y) { p_now_at_diag.moved_this_step = true; }
                        return; 
                    }
                }
            }
        }

        let am_powder = is_powder(initial_particle_type); 
        let am_liquid_or_gas = initial_props_is_liquid || initial_props_is_gas;

        if am_liquid_or_gas { 
            let viscosity = self.grid.get_particle(x,y).map(|p| p.get_material_properties().viscosity).unwrap_or(1.0);
            let dx1 = if rand::random::<f32>() < 0.5 { -1 } else { 1 }; 
            for &check_dx in &[dx1, -dx1] { 
                let side_x = x + check_dx; let side_y = y;
                if !self.grid.is_valid(side_x, side_y) { continue; } 

                if self.grid.get_particle(side_x, side_y).map_or(false, |p| p.material_type == MaterialType::EMPTY) {
                    let move_chance = if initial_props_is_liquid { (1.0 - viscosity * 0.1).max(0.1) } else { 1.0 }; 
                    if rand::random::<f32>() < move_chance {
                        self.grid.swap_particles(x, y, side_x, side_y);
                        if let Some(p_now_at_side) = self.grid.get_particle_mut(side_x, side_y) { p_now_at_side.moved_this_step = true; }
                        return; 
                    }
                } else if initial_props_is_liquid && self.grid.get_particle(side_x,side_y).map_or(false, |p|is_liquid(p.material_type)) && initial_particle_moved_this_step {
                    let push_beyond_x = side_x + check_dx; 
                    if self.grid.is_valid(push_beyond_x, y) && self.grid.get_particle(push_beyond_x, y).map_or(false, |p| p.material_type == MaterialType::EMPTY) {
                        if rand::random::<f32>() < (0.5 / viscosity) { 
                            let particle_to_push_clone = self.grid.get_particle(side_x, y).unwrap().clone();
                            let current_particle_clone = self.grid.get_particle(x, y).unwrap().clone();
                            self.grid.set_particle(push_beyond_x, y, particle_to_push_clone);
                            if let Some(p) = self.grid.get_particle_mut(push_beyond_x, y) { p.moved_this_step = true; }
                            self.grid.set_particle(side_x, y, current_particle_clone);
                            if let Some(p) = self.grid.get_particle_mut(side_x, y) { p.moved_this_step = true; }
                            self.grid.set_particle(x, y, Particle::new(x, y, MaterialType::EMPTY, AMBIENT_TEMP));
                            return; 
                        }
                    }
                }
            }
        } else if am_powder && vert_dir == 1 { 
            if let Some(p_below) = self.grid.get_particle(x, y + 1) {
                if p_below.material_type != MaterialType::EMPTY && p_below.material_type != MaterialType::GENERATOR {
                    let dx1 = if rand::random::<f32>() < 0.5 { -1 } else { 1 }; 
                    for &check_dx in &[dx1, -dx1] { 
                        let pile_x = x + check_dx; let pile_y = y + 1; 
                        if self.grid.is_valid(pile_x, pile_y) && self.grid.get_particle(pile_x, pile_y).map_or(false, |p| p.material_type == MaterialType::EMPTY) {
                            self.grid.swap_particles(x, y, pile_x, pile_y);
                            if let Some(p_now_at_pile) = self.grid.get_particle_mut(pile_x, pile_y) { p_now_at_pile.moved_this_step = true; }
                            return; 
                        }
                    }
                }
            }
        }
    }

    // --- Public API for Game Interaction ---

    /// Places particles in a circular area on the grid.
    ///
    /// This method is typically used by the game to allow users to "paint" particles onto the simulation grid.
    /// It ensures that `GENERATOR` particles are not overwritten unless the `ERASER` tool is used.
    ///
    /// # Arguments
    /// * `center_x` - The x-coordinate of the circle's center.
    /// * `center_y` - The y-coordinate of the circle's center.
    /// * `radius` - Radius of the circle in grid cells.
    /// * `material_type` - The `MaterialType` of the particles to place.
    /// * `brush_temp_override` - Optional temperature for the placed particles. If `None`,
    ///   a default temperature is used (e.g., `LAVA_BRUSH_TEMP` for `LAVA`, `AMBIENT_TEMP` otherwise).
    pub fn place_particle_circle(
        &mut self, 
        center_x: i32, 
        center_y: i32, 
        radius: i32, 
        material_type: MaterialType, 
        brush_temp_override: Option<f32>
    ) {
        let radius_sq = (radius * radius) as f32; 

        for dy in -radius..=radius {
            for dx in -radius..=radius {
                let px = center_x + dx;
                let py = center_y + dy;

                let dist_sq = (dx * dx + dy * dy) as f32; 

                if dist_sq <= radius_sq { 
                    if self.grid.is_valid(px, py) {
                        if let Some(existing_particle) = self.grid.get_particle(px, py) {
                            if existing_particle.material_type == MaterialType::GENERATOR && material_type != MaterialType::ERASER {
                                continue; 
                            }
                        }

                        let initial_temp = if let Some(temp_override) = brush_temp_override {
                            temp_override
                        } else if material_type == MaterialType::LAVA { 
                            LAVA_BRUSH_TEMP 
                        } else {
                            AMBIENT_TEMP 
                        };

                        let new_particle = if material_type == MaterialType::ERASER {
                            Particle::new(px, py, MaterialType::EMPTY, AMBIENT_TEMP)
                        } else {
                            Particle::new(px, py, material_type, initial_temp)
                        };
                        self.grid.set_particle(px, py, new_particle);
                    }
                }
            }
        }
    }

    /// Clears the entire simulation grid.
    ///
    /// All particles in the grid are replaced with `EMPTY` particles at `AMBIENT_TEMP`.
    /// The `shuffled_column_order` is also reset and re-shuffled.
    pub fn clear_grid(&mut self) {
        let width = self.grid.width;
        let height = self.grid.height;
        self.grid = Grid::new(width, height); 
        self.shuffled_column_order = (0..width).collect();
        self.shuffled_column_order.shuffle(&mut thread_rng());
    }

    /// Retrieves formatted information about the particle at the given (`x`, `y`) coordinates.
    ///
    /// This is useful for UI display, showing details like material name, temperature, lifespan, and burning status.
    ///
    /// # Arguments
    /// * `x` - The x-coordinate of the particle.
    /// * `y` - The y-coordinate of the particle.
    ///
    /// # Returns
    /// An `Option<String>` containing:
    /// - `"Coords: OOB"` if coordinates are out of bounds.
    /// - `"Material: Empty"` if the cell contains an `EMPTY` particle.
    /// - A formatted string with particle details if a non-empty particle is found.
    /// - `"Grid cell data error"` if an unexpected issue occurs (e.g., valid coordinates but no particle data).
    pub fn get_particle_info_for_display(&self, x: i32, y: i32) -> Option<String> {
        if !self.grid.is_valid(x, y) {
            return Some("Coords: OOB".to_string());
        }

        if let Some(p) = self.grid.get_particle(x, y) {
            if p.material_type != MaterialType::EMPTY {
                let props = get_material_properties(p.material_type);
                let name = props.name;
                let life_str = p.life_remaining_seconds.map_or("N/A".to_string(), |l| format!("{:.1}", l));
                Some(format!(
                    "Material: {}, Temp: {:.1}°C, Life: {}s, Burning: {}",
                    name, p.temperature, life_str, p.burning
                ))
            } else {
                Some("Material: Empty".to_string())
            }
        } else {
            Some("Grid cell data error".to_string()) 
        }
    }
}
