[package]
name = "sand_simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
pixels = "0.13.0"      # Efficient pixel buffer rendering
winit = "0.28.6"       # Window management & event handling
rand = "0.8.5"         # Random number generation
fontdue = "0.7.3"      # Font rendering